{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.programs.waystt;
in {
  options.programs.waystt = {
    enable = mkEnableOption "waystt - Wayland speech-to-text tool";

    package = mkOption {
      type = types.package;
      description = "The waystt package to use.";
    };

    settings = mkOption {
      type = types.attrsOf types.str;
      default = {};
      description = "Environment variables for waystt configuration.";
    };

    openaiKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to file containing OPENAI_API_KEY.";
    };
  };

  config = mkIf cfg.enable {
    home = {
      packages = [
        cfg.package
        pkgs.wtype
        pkgs.wl-clipboard
      ];

      activation.waysttEnv = lib.hm.dag.entryAfter ["writeBoundary" "sops-nix"] ''
        envFile="$HOME/.config/waystt/.env"
        mkdir -p "$(dirname "$envFile")"
        {
          echo "# waystt configuration (generated by home-manager)"
          echo ""
          ${concatStringsSep "\n" (mapAttrsToList (k: v: ''echo "${k}=${v}"'') cfg.settings)}
          ${optionalString (cfg.openaiKeyFile != null) ''
          if [ -r "${cfg.openaiKeyFile}" ]; then
            echo "OPENAI_API_KEY=$(cat "${cfg.openaiKeyFile}")"
          fi
        ''}
        } > "$envFile"
      '';
    };
  };
}
