name: "Setup Nix"
description: "Install Nix, configure caches, and set up Cachix"

inputs:
  cachix-auth-token:
    description: "Cachix auth token"
    required: true
  platform:
    description: "Platform: 'linux' or 'darwin'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = ${{ inputs.platform == 'linux' && 'https://hyprland.cachix.org https://nixpkgs-wayland.cachix.org https://chaotic-nyx.cachix.org/ https://vicinae.cachix.org' || '' }} https://devenv.cachix.org https://pre-commit-hooks.cachix.org https://danielgafni.cachix.org https://nix-community.cachix.org https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= pre-commit-hooks.cachix.org-1:Pkk3Panw5AW24TOv6kz3PvLhlH8puAsJTBbOPmBo7Rc= danielgafni.cachix.org-1:ZdXJoJEqeiGGOf/MtAiocqj7/vvFbA2MWFVwopJ2WQM= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= ${{ inputs.platform == 'linux' && 'hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8 vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc=' || '' }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v17
      with:
        name: danielgafni
        authToken: ${{ inputs.cachix-auth-token }}
        useDaemon: true
        extraPullNames: ${{ inputs.platform == 'linux' && 'hyprland,nixpkgs-wayland,chaotic-nyx,vicinae,' || '' }}devenv,pre-commit-hooks,nix-community

    - name: Update channels
      shell: bash
      run: nix-channel --update
