{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:
with lib; let
  cfg = config.programs.waystt;

  crane = inputs.crane.mkLib pkgs;

  src = inputs.waystt;

  # Common arguments shared between deps and main build
  commonArgs = {
    inherit src;
    pname = "waystt";
    strictDeps = true;

    nativeBuildInputs = with pkgs; [
      pkg-config
      cmake
      git
    ];

    buildInputs = with pkgs; [
      # Audio dependencies
      alsa-lib
      pipewire

      # OpenSSL for reqwest/tonic TLS
      openssl

      # whisper-rs needs these
      llvmPackages.libclang
    ];

    # whisper-rs build needs this
    LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
  };

  # Build dependencies first (this is where whisper-rs-sys gets compiled)
  cargoArtifacts = crane.buildDepsOnly commonArgs;

  # Build the final package
  waystt = crane.buildPackage (commonArgs
    // {
      inherit cargoArtifacts;

      meta = {
        description = "A minimal signal-driven speech-to-text tool for Wayland environments with PipeWire audio";
        homepage = "https://github.com/sevos/waystt";
        license = licenses.gpl3Plus;
        platforms = platforms.linux;
        maintainers = [];
      };
    });
in {
  options.programs.waystt = {
    enable = mkEnableOption "waystt - Wayland speech-to-text tool";

    package = mkOption {
      type = types.package;
      default = waystt;
      description = "The waystt package to use.";
    };

    settings = mkOption {
      type = types.attrsOf types.str;
      default = {};
      example = literalExpression ''
        {
          TRANSCRIPTION_PROVIDER = "local";
          WHISPER_MODEL = "ggml-base.en.bin";
        }
      '';
      description = "Environment variables for waystt configuration.";
    };

    openaiKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      example = literalExpression ''config.sops.secrets.OPENAI_API_KEY.path'';
      description = "Path to file containing OPENAI_API_KEY (e.g., sops secret path).";
    };
  };

  config = mkIf cfg.enable {
    home = {
      packages = [
        cfg.package
        pkgs.wtype # for direct typing output (supports unicode/non-ascii)
        pkgs.wl-clipboard # for clipboard output (wl-copy)
      ];

      # Generate .env file via activation script so we can read sops secrets at runtime
      activation.waysttEnv = lib.hm.dag.entryAfter ["writeBoundary" "sops-nix"] ''
        envFile="$HOME/.config/waystt/.env"
        mkdir -p "$(dirname "$envFile")"
        {
          echo "# waystt configuration (generated by home-manager)"
          echo "# Models are stored in: ~/.local/share/applications/waystt/models/"
          echo "# Run 'waystt --download-model' to download the configured model"
          echo ""
          ${concatStringsSep "\n" (mapAttrsToList (k: v: ''echo "${k}=${v}"'') cfg.settings)}
          ${optionalString (cfg.openaiKeyFile != null) ''
          if [ -r "${cfg.openaiKeyFile}" ]; then
            echo "OPENAI_API_KEY=$(cat "${cfg.openaiKeyFile}")"
          fi
        ''}
        } > "$envFile"
      '';
    };
  };
}
