name: "Build"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

env:
  NIXPKGS_ALLOW_UNFREE: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Flake Check
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v16
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        useDaemon: true
    - run: nix-channel --update
    - run: nix flake check

  build-nixos:
    strategy:
      matrix:
        host:
          - DanPC
          - framnix
    runs-on: ubuntu-latest
    name: Build NixOS for ${{ matrix.host }}
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://hyprland.cachix.org https://nixpkgs-wayland.cachix.org https://pre-commit-hooks.cachix.org https://danielgafni.cachix.org https://nix-community.cachix.org https://zed.cachix.org/ https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= pre-commit-hooks.cachix.org-1:Pkk3Panw5AW24TOv6kz3PvLhlH8puAsJTBbOPmBo7Rc= danielgafni.cachix.org-1:ZdXJoJEqeiGGOf/MtAiocqj7/vvFbA2MWFVwopJ2WQM= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= zed.cachix.org-1:/pHQ6dpMsAZk2DiP4WCL0p9YDNKWj2Q5FL20bNmw1cU=
    - uses: cachix/cachix-action@v16
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        useDaemon: true
        extraPullNames: hyprland,nixpkgs-wayland,pre-commit-hooks,nix-community,anyrun,zed
    - run: nix-channel --update
    - run: nix build --impure .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  build-home:
    strategy:
      matrix:
        host-users:
          - host: DanPC
            user: dan
          - host: framnix
            user: dan
          - host: framnix
            user: underdel
    runs-on: ubuntu-latest
    name: Build Home for ${{ matrix.host-users.user }}@${{ matrix.host-users.host }}
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://hyprland.cachix.org https://nixpkgs-wayland.cachix.org https://pre-commit-hooks.cachix.org https://danielgafni.cachix.org https://nix-community.cachix.org https://zed.cachix.org/ https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= pre-commit-hooks.cachix.org-1:Pkk3Panw5AW24TOv6kz3PvLhlH8puAsJTBbOPmBo7Rc= danielgafni.cachix.org-1:ZdXJoJEqeiGGOf/MtAiocqj7/vvFbA2MWFVwopJ2WQM= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= zed.cachix.org-1:/pHQ6dpMsAZk2DiP4WCL0p9YDNKWj2Q5FL20bNmw1cU=
    - uses: cachix/cachix-action@v16
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        useDaemon: true
        extraPullNames: hyprland,nixpkgs-wayland,pre-commit-hooks,nix-community,anyrun,zed
    - run: nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    - run: nix-channel --update
    - run: nix-env -i home-manager
    - run: home-manager --flake .#${{ matrix.host-users.user }}@${{ matrix.host-users.host }} build --impure

  result:
    needs:
      - test
      - build-nixos
      - build-home
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build succeeded"
