name: "Build"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

env:
  NIXPKGS_ALLOW_UNFREE: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Flake Check
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-nix
      with:
        cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
        platform: linux
    - run: nix build .#checks.x86_64-linux.pre-commit-check

  build-nixos:
    strategy:
      matrix:
        host:
          - DanPC
          - framnix
    runs-on: ubuntu-latest
    name: Build NixOS for ${{ matrix.host }}
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-nix
      with:
        cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
        platform: linux
    - run: nix build --impure .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  build-darwin:
    runs-on: macos-latest
    name: Build Darwin for MacBook
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-nix
      with:
        cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
        platform: darwin
    - run: nix build .#darwinConfigurations.MacBook.system

  build-home:
    strategy:
      matrix:
        include:
          - name: "dan@DanPC"
            runner: ubuntu-latest
            platform: linux
          - name: "dan@framnix"
            runner: ubuntu-latest
            platform: linux
          - name: "dan@MacBook"
            runner: macos-latest
            platform: darwin
    runs-on: ${{ matrix.runner }}
    name: Build Home for ${{ matrix.name }}
    steps:
    - name: Free Disk Space (Ubuntu)
      if: runner.os == 'Linux'
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-nix
      with:
        cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
        platform: ${{ matrix.platform }}
    - run: nix build .#homeConfigurations."${{ matrix.name }}".activationPackage

  result:
    needs:
      - test
      - build-nixos
      - build-darwin
      - build-home
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build succeeded"
