name: "Test"
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        host: [DanPC, framnix]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: cachix/cachix-action@v14
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
    - run: nix flake check

