name: "Test"
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        host: [DanPC, framnix]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-channel --add https://nixos.org/channels/nixos-unstable
    - run: nix-channel --update
    - run: nix-env -i nixpkgs#nix-output-monitor
    - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --log-format internal-json -v |& nom --json
    - run: nix flake check
