name: "Test"
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        host: [DanPC, framnix]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nixos-rebuild --flake .#${{ matrix.host }} build
    - run: nix flake check

