name: "Test"
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        host: [DanPC, framnix]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nixos-rebuild --flake .#${{ matrix.host }} build
    - run: nix flake check

